import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.content}>
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to the site!</h1>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit deleniti
        hic fugiat quidem beatae suscipit nostrum saepe dolore deserunt
        cupiditate, inventore ut perferendis excepturi itaque amet dolor rerum
        sequi adipisci.
      </p>
    </div>
  );
}
